# Generated by Django 5.2.15 on 2026-06-29 13:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vendorprofile_latitude_vendorprofile_longitude_and_more'),
        ('catalog', '0002_home_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=40)),
                ('hotspot_yaw', models.FloatField(default=0)),
                ('hotspot_pitch', models.FloatField(default=0)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='VenuePanorama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Main hall', max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='venue_panoramas/')),
                ('image_url', models.CharField(blank=True, help_text='External 360 image URL when no upload is set.', max_length=500)),
                ('initial_yaw', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='homefeatureditem',
            new_name='catalog_hom_section_a75342_idx',
            old_name='catalog_hom_section_0f3e2d_idx',
        ),
        migrations.AddField(
            model_name='diningtable',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_tables', to='accounts.vendorprofile'),
        ),
        migrations.AddField(
            model_name='venuepanorama',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='accounts.vendorprofile'),
        ),
        migrations.AddField(
            model_name='diningtable',
            name='panorama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='catalog.venuepanorama'),
        ),
        migrations.AlterUniqueTogether(
            name='diningtable',
            unique_together={('vendor', 'label')},
        ),
    ]
