# Generated by Django 5.2.15 on 2026-06-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peykassignment',
            options={'ordering': ['-assigned_at']},
        ),
    ]
