# Generated by Django 5.2.15 on 2026-06-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phone_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='supports_dine_in',
            field=models.BooleanField(default=False),
        ),
    ]
