# Generated by Django 5.2.15 on 2026-06-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vendorprofile_latitude_vendorprofile_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
