# Generated by Django 5.2.15 on 2026-06-13 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue', models.BigIntegerField(default=0)),
                ('avg_order_value', models.BigIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.vendorprofile')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('vendor', 'period', 'period_start')},
            },
        ),
    ]
