# Generated by Django 5.2.15 on 2026-06-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('cash', 'Cash'), ('card_in_person', 'Card in Person'), ('wallet', 'Wallet')], max_length=20),
        ),
    ]
